### ISSUE TITLE
Creating a temporary issuer account not possible. 

### ISSUE THREAD

**Issue by chuuck** [google-pay/gpay-loyaltyapi-demo#1]
During completion of [Step 3](https://codelabs.developers.google.com/passes-loyaltyapi#2). Section "Create a temporary issuer account". It is required to create a temporary issuer account, after accessing the stated [link](https://gpay-loyaltyapi-codelab.web.app/issuers) and entering an email address, the error "Failed to create a temporary issuer account." always appears.

**Comment by socsieng** [comment]
This should now be resolved.

Please try again.

**Comment by chuuck** [comment]
Great it works now, thank you!

**Comment by chagemann** [comment]
I've got this issue today too.

**Comment by socsieng** [comment]
FYI @JlUgia @stephenmcd

**Comment by floschu** [comment]
Currently trying out the [Google Wallet Codelab](https://codelabs.developers.google.com/add-to-wallet-android), but cannot create temporary issuer account for testing, also getting a "Create a temporary issuer account".

**Comment by chagemann** [comment]
Works for me on https://wallet-lab-tools.web.app/issuers

**Comment by JlUgia** [comment]
That's right, g.co/wallet/lab-tools has the updated site to create test issuer accounts.

**Comment by floschu** [comment]
Ah okay today it just worked. Maybe it was issues due to increased Google IO traffic.
