### ISSUE TITLE
Merchant center

### ISSUE THREAD

**Issue by advatar** [google-pay/gpay-loyaltyapi-demo#2]
It does not work to create a new loyalty program - it is just blank, no create new. Granted, this is not an issue with this Codelab but it is blocking running it.

**Comment by advatar** [comment]
![image](https://user-images.githubusercontent.com/28670/128609424-b9f74fa0-9744-41b1-9ebb-25a488a365f8.png)

**Comment by socsieng** [comment]
It's the **Create new** button in the top left hand corner, above the menu.
